# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArQ0ReG1d3s4LtlvKUBTrvLmrPP_XFqQ
"""

!pip install forex-python

from forex_python.converter import CurrencyRates

# Create a CurrencyRates object
cr = CurrencyRates()

# Input from user
from_currency = input("Enter base currency (e.g., USD): ").upper()
to_currency = input("Enter target currency (e.g., INR): ").upper()
amount = float(input(f"Enter amount in {from_currency}: "))

# Perform conversion
try:
    result = cr.convert(from_currency, to_currency, amount)
    print(f"\n{amount} {from_currency} = {round(result, 2)} {to_currency}")
except Exception as e:
    print("Error:", e)
